
#DB
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.144:3306/team_b
    username: team_b
    password: green502
  #mybatisz


mybatis:
  type-aliases-package: com.
  mapper-locations: mapper/**/*.xml

#SWAGGER
springdoc:

  swagger-ui:
    path: /swagger.html
    operations-sorter : method


file:
  dir: \home\smart_grade

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mariadb://localhost:3306/smart_grade_test
    username: root
    password: green502
  sql:
    init:
      mode: always
      schema-locations: classpath:init/schema.sql
      data-locations: classpath:init/data.sql